import { chromium } from "playwright";
const [url, out] = process.argv.slice(2);
const browser = await chromium.launch({ args: ["--use-angle=swiftshader", "--enable-unsafe-swiftshader", "--ignore-gpu-blocklist"] });
const page = await browser.newPage({ viewport: { width: 1180, height: 760 } });
const logs = [];
page.on("console", (m) => { const t = m.text(); if ((m.type() === "error" || m.type() === "warning") && !t.includes("404") && !t.includes("GL Driver") && !t.includes("std140") && !t.includes("Binding sampler")) logs.push(`${m.type()}: ${t.slice(0, 300)}`); });
page.on("pageerror", (e) => logs.push(`pageerror: ${e.message.slice(0, 300)}`));
await page.goto(url);
await page.waitForFunction(() => window.__viewer, null, { timeout: 90000 });
await page.waitForTimeout(9000);
await page.screenshot({ path: `${out}_colour.png` });
await page.click("#map", { position: { x: 500, y: 350 } });
await page.waitForTimeout(4000);
await page.click("#doubtOn"); await page.waitForTimeout(3000);
await page.screenshot({ path: `${out}_doubt.png` });
await page.keyboard.press("]"); await page.waitForTimeout(5000);
console.log("year after ]:", await page.evaluate(() => document.getElementById("yearOut").textContent), "| note:", await page.evaluate(() => document.getElementById("yearNote").textContent));
console.log("readout:", await page.evaluate(() => document.getElementById("readout").innerText.replace(/\n/g, " / ")), "| where:", await page.evaluate(() => document.getElementById("pixelWhere").textContent));
await page.hover("#pixelBody svg", { position: { x: 120, y: 40 } }); await page.waitForTimeout(300);
await page.locator("aside").screenshot({ path: `${out}_rail.png` });
console.log("logs:", logs.slice(0, 10).join("\n") || "none");
await browser.close();
